// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weatherRequest.proto

package proto.weather;

/**
 * Protobuf type {@code ProtoTimeBlock}
 */
public final class ProtoTimeBlock extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProtoTimeBlock)
    ProtoTimeBlockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoTimeBlock.newBuilder() to construct.
  private ProtoTimeBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoTimeBlock() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoTimeBlock();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoTimeBlock(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timeStart_ != null) {
              subBuilder = timeStart_.toBuilder();
            }
            timeStart_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timeStart_);
              timeStart_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timeEnd_ != null) {
              subBuilder = timeEnd_.toBuilder();
            }
            timeEnd_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timeEnd_);
              timeEnd_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.weather.WeatherRequest.internal_static_ProtoTimeBlock_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.weather.WeatherRequest.internal_static_ProtoTimeBlock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.weather.ProtoTimeBlock.class, proto.weather.ProtoTimeBlock.Builder.class);
  }

  public static final int TIMESTART_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timeStart_;
  /**
   * <code>.google.protobuf.Timestamp timeStart = 1;</code>
   * @return Whether the timeStart field is set.
   */
  @java.lang.Override
  public boolean hasTimeStart() {
    return timeStart_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timeStart = 1;</code>
   * @return The timeStart.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimeStart() {
    return timeStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStart_;
  }
  /**
   * <code>.google.protobuf.Timestamp timeStart = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeStartOrBuilder() {
    return getTimeStart();
  }

  public static final int TIMEEND_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp timeEnd_;
  /**
   * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
   * @return Whether the timeEnd field is set.
   */
  @java.lang.Override
  public boolean hasTimeEnd() {
    return timeEnd_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
   * @return The timeEnd.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimeEnd() {
    return timeEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeEnd_;
  }
  /**
   * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeEndOrBuilder() {
    return getTimeEnd();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeStart_ != null) {
      output.writeMessage(1, getTimeStart());
    }
    if (timeEnd_ != null) {
      output.writeMessage(2, getTimeEnd());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeStart_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimeStart());
    }
    if (timeEnd_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimeEnd());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.weather.ProtoTimeBlock)) {
      return super.equals(obj);
    }
    proto.weather.ProtoTimeBlock other = (proto.weather.ProtoTimeBlock) obj;

    if (hasTimeStart() != other.hasTimeStart()) return false;
    if (hasTimeStart()) {
      if (!getTimeStart()
          .equals(other.getTimeStart())) return false;
    }
    if (hasTimeEnd() != other.hasTimeEnd()) return false;
    if (hasTimeEnd()) {
      if (!getTimeEnd()
          .equals(other.getTimeEnd())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTimeStart()) {
      hash = (37 * hash) + TIMESTART_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStart().hashCode();
    }
    if (hasTimeEnd()) {
      hash = (37 * hash) + TIMEEND_FIELD_NUMBER;
      hash = (53 * hash) + getTimeEnd().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.weather.ProtoTimeBlock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.weather.ProtoTimeBlock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.weather.ProtoTimeBlock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.weather.ProtoTimeBlock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.weather.ProtoTimeBlock prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProtoTimeBlock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoTimeBlock)
      proto.weather.ProtoTimeBlockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.weather.WeatherRequest.internal_static_ProtoTimeBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.weather.WeatherRequest.internal_static_ProtoTimeBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.weather.ProtoTimeBlock.class, proto.weather.ProtoTimeBlock.Builder.class);
    }

    // Construct using proto.weather.ProtoTimeBlock.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (timeStartBuilder_ == null) {
        timeStart_ = null;
      } else {
        timeStart_ = null;
        timeStartBuilder_ = null;
      }
      if (timeEndBuilder_ == null) {
        timeEnd_ = null;
      } else {
        timeEnd_ = null;
        timeEndBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.weather.WeatherRequest.internal_static_ProtoTimeBlock_descriptor;
    }

    @java.lang.Override
    public proto.weather.ProtoTimeBlock getDefaultInstanceForType() {
      return proto.weather.ProtoTimeBlock.getDefaultInstance();
    }

    @java.lang.Override
    public proto.weather.ProtoTimeBlock build() {
      proto.weather.ProtoTimeBlock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.weather.ProtoTimeBlock buildPartial() {
      proto.weather.ProtoTimeBlock result = new proto.weather.ProtoTimeBlock(this);
      if (timeStartBuilder_ == null) {
        result.timeStart_ = timeStart_;
      } else {
        result.timeStart_ = timeStartBuilder_.build();
      }
      if (timeEndBuilder_ == null) {
        result.timeEnd_ = timeEnd_;
      } else {
        result.timeEnd_ = timeEndBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.weather.ProtoTimeBlock) {
        return mergeFrom((proto.weather.ProtoTimeBlock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.weather.ProtoTimeBlock other) {
      if (other == proto.weather.ProtoTimeBlock.getDefaultInstance()) return this;
      if (other.hasTimeStart()) {
        mergeTimeStart(other.getTimeStart());
      }
      if (other.hasTimeEnd()) {
        mergeTimeEnd(other.getTimeEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.weather.ProtoTimeBlock parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.weather.ProtoTimeBlock) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp timeStart_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStartBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     * @return Whether the timeStart field is set.
     */
    public boolean hasTimeStart() {
      return timeStartBuilder_ != null || timeStart_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     * @return The timeStart.
     */
    public com.google.protobuf.Timestamp getTimeStart() {
      if (timeStartBuilder_ == null) {
        return timeStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStart_;
      } else {
        return timeStartBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    public Builder setTimeStart(com.google.protobuf.Timestamp value) {
      if (timeStartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStart_ = value;
        onChanged();
      } else {
        timeStartBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    public Builder setTimeStart(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeStartBuilder_ == null) {
        timeStart_ = builderForValue.build();
        onChanged();
      } else {
        timeStartBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    public Builder mergeTimeStart(com.google.protobuf.Timestamp value) {
      if (timeStartBuilder_ == null) {
        if (timeStart_ != null) {
          timeStart_ =
            com.google.protobuf.Timestamp.newBuilder(timeStart_).mergeFrom(value).buildPartial();
        } else {
          timeStart_ = value;
        }
        onChanged();
      } else {
        timeStartBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    public Builder clearTimeStart() {
      if (timeStartBuilder_ == null) {
        timeStart_ = null;
        onChanged();
      } else {
        timeStart_ = null;
        timeStartBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeStartBuilder() {
      
      onChanged();
      return getTimeStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeStartOrBuilder() {
      if (timeStartBuilder_ != null) {
        return timeStartBuilder_.getMessageOrBuilder();
      } else {
        return timeStart_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timeStart_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timeStart = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeStartFieldBuilder() {
      if (timeStartBuilder_ == null) {
        timeStartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimeStart(),
                getParentForChildren(),
                isClean());
        timeStart_ = null;
      }
      return timeStartBuilder_;
    }

    private com.google.protobuf.Timestamp timeEnd_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeEndBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     * @return Whether the timeEnd field is set.
     */
    public boolean hasTimeEnd() {
      return timeEndBuilder_ != null || timeEnd_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     * @return The timeEnd.
     */
    public com.google.protobuf.Timestamp getTimeEnd() {
      if (timeEndBuilder_ == null) {
        return timeEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeEnd_;
      } else {
        return timeEndBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    public Builder setTimeEnd(com.google.protobuf.Timestamp value) {
      if (timeEndBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeEnd_ = value;
        onChanged();
      } else {
        timeEndBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    public Builder setTimeEnd(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeEndBuilder_ == null) {
        timeEnd_ = builderForValue.build();
        onChanged();
      } else {
        timeEndBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    public Builder mergeTimeEnd(com.google.protobuf.Timestamp value) {
      if (timeEndBuilder_ == null) {
        if (timeEnd_ != null) {
          timeEnd_ =
            com.google.protobuf.Timestamp.newBuilder(timeEnd_).mergeFrom(value).buildPartial();
        } else {
          timeEnd_ = value;
        }
        onChanged();
      } else {
        timeEndBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    public Builder clearTimeEnd() {
      if (timeEndBuilder_ == null) {
        timeEnd_ = null;
        onChanged();
      } else {
        timeEnd_ = null;
        timeEndBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeEndBuilder() {
      
      onChanged();
      return getTimeEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeEndOrBuilder() {
      if (timeEndBuilder_ != null) {
        return timeEndBuilder_.getMessageOrBuilder();
      } else {
        return timeEnd_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timeEnd_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeEndFieldBuilder() {
      if (timeEndBuilder_ == null) {
        timeEndBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimeEnd(),
                getParentForChildren(),
                isClean());
        timeEnd_ = null;
      }
      return timeEndBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProtoTimeBlock)
  }

  // @@protoc_insertion_point(class_scope:ProtoTimeBlock)
  private static final proto.weather.ProtoTimeBlock DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.weather.ProtoTimeBlock();
  }

  public static proto.weather.ProtoTimeBlock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoTimeBlock>
      PARSER = new com.google.protobuf.AbstractParser<ProtoTimeBlock>() {
    @java.lang.Override
    public ProtoTimeBlock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoTimeBlock(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoTimeBlock> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoTimeBlock> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.weather.ProtoTimeBlock getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

