// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weatherRequest.proto

package proto.weather;

public interface ProtoWeatherDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoWeatherDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timeunit = 1;</code>
   * @return The timeunit.
   */
  java.lang.String getTimeunit();
  /**
   * <code>string timeunit = 1;</code>
   * @return The bytes for timeunit.
   */
  com.google.protobuf.ByteString
      getTimeunitBytes();

  /**
   * <code>int32 timeAmount = 2;</code>
   * @return The timeAmount.
   */
  int getTimeAmount();
}
