// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weatherRequest.proto

package proto.weather;

public interface ProtoWeatherDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoWeatherData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProtoWeatherDataPoint WeatherDataPoints = 1;</code>
   */
  java.util.List<proto.weather.ProtoWeatherDataPoint> 
      getWeatherDataPointsList();
  /**
   * <code>repeated .ProtoWeatherDataPoint WeatherDataPoints = 1;</code>
   */
  proto.weather.ProtoWeatherDataPoint getWeatherDataPoints(int index);
  /**
   * <code>repeated .ProtoWeatherDataPoint WeatherDataPoints = 1;</code>
   */
  int getWeatherDataPointsCount();
  /**
   * <code>repeated .ProtoWeatherDataPoint WeatherDataPoints = 1;</code>
   */
  java.util.List<? extends proto.weather.ProtoWeatherDataPointOrBuilder> 
      getWeatherDataPointsOrBuilderList();
  /**
   * <code>repeated .ProtoWeatherDataPoint WeatherDataPoints = 1;</code>
   */
  proto.weather.ProtoWeatherDataPointOrBuilder getWeatherDataPointsOrBuilder(
      int index);
}
