// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weatherRequest.proto

package proto.weather;

public interface ProtoTimeBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoTimeBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timeStart = 1;</code>
   * @return Whether the timeStart field is set.
   */
  boolean hasTimeStart();
  /**
   * <code>.google.protobuf.Timestamp timeStart = 1;</code>
   * @return The timeStart.
   */
  com.google.protobuf.Timestamp getTimeStart();
  /**
   * <code>.google.protobuf.Timestamp timeStart = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStartOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
   * @return Whether the timeEnd field is set.
   */
  boolean hasTimeEnd();
  /**
   * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
   * @return The timeEnd.
   */
  com.google.protobuf.Timestamp getTimeEnd();
  /**
   * <code>.google.protobuf.Timestamp timeEnd = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeEndOrBuilder();
}
