// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weatherRequest.proto

package proto.weather;

/**
 * Protobuf type {@code ProtoWeatherDataRequest}
 */
public final class ProtoWeatherDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProtoWeatherDataRequest)
    ProtoWeatherDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoWeatherDataRequest.newBuilder() to construct.
  private ProtoWeatherDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoWeatherDataRequest() {
    timeunit_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoWeatherDataRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoWeatherDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            timeunit_ = s;
            break;
          }
          case 16: {

            timeAmount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.weather.WeatherRequest.internal_static_ProtoWeatherDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.weather.WeatherRequest.internal_static_ProtoWeatherDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.weather.ProtoWeatherDataRequest.class, proto.weather.ProtoWeatherDataRequest.Builder.class);
  }

  public static final int TIMEUNIT_FIELD_NUMBER = 1;
  private volatile java.lang.Object timeunit_;
  /**
   * <code>string timeunit = 1;</code>
   * @return The timeunit.
   */
  @java.lang.Override
  public java.lang.String getTimeunit() {
    java.lang.Object ref = timeunit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeunit_ = s;
      return s;
    }
  }
  /**
   * <code>string timeunit = 1;</code>
   * @return The bytes for timeunit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeunitBytes() {
    java.lang.Object ref = timeunit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeunit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEAMOUNT_FIELD_NUMBER = 2;
  private int timeAmount_;
  /**
   * <code>int32 timeAmount = 2;</code>
   * @return The timeAmount.
   */
  @java.lang.Override
  public int getTimeAmount() {
    return timeAmount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeunit_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeunit_);
    }
    if (timeAmount_ != 0) {
      output.writeInt32(2, timeAmount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeunit_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeunit_);
    }
    if (timeAmount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeAmount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.weather.ProtoWeatherDataRequest)) {
      return super.equals(obj);
    }
    proto.weather.ProtoWeatherDataRequest other = (proto.weather.ProtoWeatherDataRequest) obj;

    if (!getTimeunit()
        .equals(other.getTimeunit())) return false;
    if (getTimeAmount()
        != other.getTimeAmount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMEUNIT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeunit().hashCode();
    hash = (37 * hash) + TIMEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeAmount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.weather.ProtoWeatherDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.weather.ProtoWeatherDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.weather.ProtoWeatherDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.weather.ProtoWeatherDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProtoWeatherDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoWeatherDataRequest)
      proto.weather.ProtoWeatherDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.weather.WeatherRequest.internal_static_ProtoWeatherDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.weather.WeatherRequest.internal_static_ProtoWeatherDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.weather.ProtoWeatherDataRequest.class, proto.weather.ProtoWeatherDataRequest.Builder.class);
    }

    // Construct using proto.weather.ProtoWeatherDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeunit_ = "";

      timeAmount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.weather.WeatherRequest.internal_static_ProtoWeatherDataRequest_descriptor;
    }

    @java.lang.Override
    public proto.weather.ProtoWeatherDataRequest getDefaultInstanceForType() {
      return proto.weather.ProtoWeatherDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public proto.weather.ProtoWeatherDataRequest build() {
      proto.weather.ProtoWeatherDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.weather.ProtoWeatherDataRequest buildPartial() {
      proto.weather.ProtoWeatherDataRequest result = new proto.weather.ProtoWeatherDataRequest(this);
      result.timeunit_ = timeunit_;
      result.timeAmount_ = timeAmount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.weather.ProtoWeatherDataRequest) {
        return mergeFrom((proto.weather.ProtoWeatherDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.weather.ProtoWeatherDataRequest other) {
      if (other == proto.weather.ProtoWeatherDataRequest.getDefaultInstance()) return this;
      if (!other.getTimeunit().isEmpty()) {
        timeunit_ = other.timeunit_;
        onChanged();
      }
      if (other.getTimeAmount() != 0) {
        setTimeAmount(other.getTimeAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.weather.ProtoWeatherDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.weather.ProtoWeatherDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object timeunit_ = "";
    /**
     * <code>string timeunit = 1;</code>
     * @return The timeunit.
     */
    public java.lang.String getTimeunit() {
      java.lang.Object ref = timeunit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeunit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeunit = 1;</code>
     * @return The bytes for timeunit.
     */
    public com.google.protobuf.ByteString
        getTimeunitBytes() {
      java.lang.Object ref = timeunit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeunit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeunit = 1;</code>
     * @param value The timeunit to set.
     * @return This builder for chaining.
     */
    public Builder setTimeunit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeunit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeunit = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeunit() {
      
      timeunit_ = getDefaultInstance().getTimeunit();
      onChanged();
      return this;
    }
    /**
     * <code>string timeunit = 1;</code>
     * @param value The bytes for timeunit to set.
     * @return This builder for chaining.
     */
    public Builder setTimeunitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeunit_ = value;
      onChanged();
      return this;
    }

    private int timeAmount_ ;
    /**
     * <code>int32 timeAmount = 2;</code>
     * @return The timeAmount.
     */
    @java.lang.Override
    public int getTimeAmount() {
      return timeAmount_;
    }
    /**
     * <code>int32 timeAmount = 2;</code>
     * @param value The timeAmount to set.
     * @return This builder for chaining.
     */
    public Builder setTimeAmount(int value) {
      
      timeAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeAmount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeAmount() {
      
      timeAmount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProtoWeatherDataRequest)
  }

  // @@protoc_insertion_point(class_scope:ProtoWeatherDataRequest)
  private static final proto.weather.ProtoWeatherDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.weather.ProtoWeatherDataRequest();
  }

  public static proto.weather.ProtoWeatherDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoWeatherDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProtoWeatherDataRequest>() {
    @java.lang.Override
    public ProtoWeatherDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoWeatherDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoWeatherDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoWeatherDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.weather.ProtoWeatherDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

