// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weatherRequest.proto

package proto.weather;

public interface ProtoWeatherDataPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoWeatherDataPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 avgWindSpeed = 1;</code>
   * @return The avgWindSpeed.
   */
  int getAvgWindSpeed();

  /**
   * <code>int32 barometer = 2;</code>
   * @return The barometer.
   */
  int getBarometer();

  /**
   * <code>int32 battLevel = 3;</code>
   * @return The battLevel.
   */
  int getBattLevel();

  /**
   * <code>int32 insideHum = 4;</code>
   * @return The insideHum.
   */
  int getInsideHum();

  /**
   * <code>int32 insideTemp = 5;</code>
   * @return The insideTemp.
   */
  int getInsideTemp();

  /**
   * <code>int32 outsideHum = 6;</code>
   * @return The outsideHum.
   */
  int getOutsideHum();

  /**
   * <code>int32 outsideTemp = 7;</code>
   * @return The outsideTemp.
   */
  int getOutsideTemp();

  /**
   * <code>int32 rainRate = 8;</code>
   * @return The rainRate.
   */
  int getRainRate();

  /**
   * <code>int32 solarRad = 9;</code>
   * @return The solarRad.
   */
  int getSolarRad();

  /**
   * <code>.ProtoWeatherStation station = 10;</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.ProtoWeatherStation station = 10;</code>
   * @return The station.
   */
  proto.weather.ProtoWeatherStation getStation();
  /**
   * <code>.ProtoWeatherStation station = 10;</code>
   */
  proto.weather.ProtoWeatherStationOrBuilder getStationOrBuilder();

  /**
   * <code>int32 sunrise = 11;</code>
   * @return The sunrise.
   */
  int getSunrise();

  /**
   * <code>int32 sunset = 12;</code>
   * @return The sunset.
   */
  int getSunset();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 13;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 13;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 13;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>int32 ts = 14;</code>
   * @return The ts.
   */
  int getTs();

  /**
   * <code>int32 UVLevel = 15;</code>
   * @return The uVLevel.
   */
  int getUVLevel();

  /**
   * <code>int32 windSpeed = 16;</code>
   * @return The windSpeed.
   */
  int getWindSpeed();

  /**
   * <code>int32 windDir = 17;</code>
   * @return The windDir.
   */
  int getWindDir();

  /**
   * <code>int32 xmitBatt = 18;</code>
   * @return The xmitBatt.
   */
  int getXmitBatt();
}
